# Generated by Django 3.0.8 on 2020-07-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_admin', 'Can use CRUD portal.'), ('can_use_dashboard', 'Can use Dashboard that sees Log and API Graph'), ('can_see_log', 'Can see API and Transaction Logs'), ('can_make_transaction', 'Can make Transactions to API'))},
        ),
    ]
